### ISSUE TITLE
Outdated q-drawer-link in layout showcase

### ISSUE THREAD

**Issue by miquelromero** [quasarframework/quasar-play#10]
https://github.com/quasarframework/quasar-play/blob/master/src/components/showcase/layout/layout.vue
`        <q-drawer-link icon="view_quilt" to="/showcase/layout" exact>
          About Layout
        </q-drawer-link>
`

`exact` [should not be](http://quasar-framework.org/components/drawer.html#Drawer-Content) a q-drawer-link property.

**Comment by rstoenescu** [comment]
Will take care of this when upgrading Play to Quasar v0.14.

**Comment by rstoenescu** [comment]
Fixed. Will be visible when final v0.14 is released.
