### ISSUE TITLE
Remember scroll state on Quasar Play

### ISSUE THREAD

**Issue by kokizzu** [quasarframework/quasar-play#12]
When clicking one of Quasar Showcase demo on mobile devices, then pressing back, either using android back button or top left button, it always back scrolling to top instead of last scroll state, so we have to scroll again to try the next demo.

**Comment by rstoenescu** [comment]
Agreed. Will do. v0.14 allows this.

**Comment by rstoenescu** [comment]
Fixed. Will deploy the new Q Play along the final v0.14

**Comment by dcsan** [comment]
can you leave any details how to get this to work? using 14.1
from a long list, going to a page always forgets scroll point when going back

had a look at scroll-utils but see no mention
https://quasar-framework.org/components/scrolling-utils.html
