### ISSUE TITLE
No browsers detected

### ISSUE THREAD

**Issue by boustanihani** [quasarframework/quasar-play#14]
I am trying to debug a newly created Quasar project using Chrome-Dev-Tools. I start Quasar-Play and type my URL and then my App is displayed fine. But sadly in Chrome-Dev-Tools the Quasar-Play-WebView is not detected. If I open Chrome on my Phone, then all tabs are detected correctly and I am able to debug, but not using the Quasar-Play App :(

I am developing using **Ubuntu 14.04.5 64bit (Trusty LTS)** and **Nexus 5X** with **Android 7.1.2**

One small question, according to the docs => http://quasar-framework.org/guide/quasar-play-app.html
_While playing with your App in Quasar Play, Cordova functionality will currently not be available. This is due to Cordova Javascript code causing a crash in its Java container._

Will this bug be solved any time soon? It would be really great to have "hot-reloading" combined with Cordova functionality :)

P.S. Great Work!

**Comment by rstoenescu** [comment]
> "Quasar-Play-WebView is not detected"
Don't really understand what you mean. What are you referring to?

Unfortunately the "Cordova functionality will not be available" is a bug in Cordova, so it's out of Quasar's reach. Although a workaround is on the todo-list.

**Comment by boustanihani** [comment]
I mean I am not able to debug my app using Chrome Dev-tools. Using Quasar-Play I can only see my app without debugging. On the other side, if I open Chrome on my Phone, `chrome://inspect/#devices` will detect my app.

**Comment by boustanihani** [comment]
I think this is because the "Quasar-Play-App" was compiled for production. If you allow us to manually download a version of "Quasar-Play" (**APK compiled in dev mode**) from your site directly then this could solve the problem. Check.: https://github.com/phonegap/phonegap-app-developer/issues/49

**Comment by rstoenescu** [comment]
Hi,

Clone this repo, change package name in cordova/config.xml, build it and install it on your phone.

**Comment by boustanihani** [comment]
Would you consider offering an APK (compiled in dev mode) directly on your site?

**Comment by rstoenescu** [comment]
You can't remote debug apps downloaded from play store / appstore due to security reasons. That's why cloning this repo and building it is the easiest way. Nothing special about it, just build like any Quasar app. You need assistance?

**Comment by boustanihani** [comment]
Assistance would be really great :)

**Comment by boustanihani** [comment]
Thanks I managed to compile locally, do you think the workaround for the Cordova functionality will be implemented soon :) ?

**Comment by rstoenescu** [comment]
@boustanihani Will look into it again to see if there exists a solution, after v0.14. Thanks for your patience!
