### ISSUE TITLE
"Go fullscreen" button doest not appear on embedded Youtube video.

### ISSUE THREAD

**Issue by pedro-rates** [quasarframework/quasar-play#23]
Software Versions:

- Quasar Play: 0.13.7
- OS: Windows 8.1
- Node: v6.9.5
- NPM: 3.10.10
- Browsers: Does not apply
- iOS: Does not apply
- Android: 7.0
- Any other software related to your bug: does not apply

The "go fullscreen" button does not appear in the embedded youtube video. The button appear if I install the application in the phone using cordova, but not on the Quasar Play app.

The embedded videos are in the start page of the application. The button doesn't appear whatever is the phone orientation, even with the "allowfullscreen" keyword inside the "iframe" tag.

**Comment by rstoenescu** [comment]
Hi,

This has nothing to do with Quasar or Quasar Play at all. It has to do with what Youtube embedds in its script...
