### ISSUE TITLE
[Quasar play] Point wrong resource showcase Floating Action Button

### ISSUE THREAD

**Issue by phong-et** [quasarframework/quasar-play#27]
Quasar docs page : http://quasar-framework.org/components/floating-action-button.html
Bug case image : http://prntscr.com/hh6mri
Maybe correct link source of this lesson is  https://github.com/quasarframework/quasar-play/blob/master/src/components/showcase/layout/floating-action-button.vue

**Comment by rstoenescu** [comment]
Hi, Clear cache or something. It's pointing to the right source.
