### ISSUE TITLE
Not working on IOS [Iphone X]

### ISSUE THREAD

**Issue by hawkleaf** [quasarframework/quasar-play#30]
When I try to register an URL in the quasar play app (Using the QR code scanner) nothing happens. After pressing the butten the FAB button on the lower right just closes.

**Comment by lmfresneda** [comment]
Same problem here

**Comment by BenoitRanque** [comment]
Make sure you can ping your computed from your phone. If you try to access the same ip from google chrome on your mobile device, does it work?

**Comment by lmfresneda** [comment]
Yes, in mobile browser it works perfectly

**Comment by BenoitRanque** [comment]
Per [this](http://forum.quasar-framework.org/topic/1686/v0-15-news) forum post, the new starter kit renders quasar play obsolete

**Comment by lmfresneda** [comment]
Wow it's true, thanks for notice!

**Comment by rstoenescu** [comment]
As indicated, don't use Quasar Play with v0.15. It's obsolete. CLI will run your app directly on your phone or emulator. Read docs. Thanks

**Comment by hbb520** [comment]
131

**Comment by hbb520** [comment]
123

**Comment by hbb520** [comment]
123
