### ISSUE TITLE
<q-carousel-slide> - did you register the component correctly

### ISSUE THREAD

**Issue by simranjain1507** [quasarframework/quasar-play#42]
##template

```
<q-carousel class="text-white">
            <q-carousel-slide>
             ....
            </q-carousel-slide>
          </q-carousel>
```
##script
```
import { QCarousel, QCarouselSlide } from 'quasar'
export default{
components: {
QCarousel,
    QCarouselSlide,
}
}
```
I have added the components correctly, still it shows me the following error:

> <q-carousel-slide> - did you register the component correctly

> "export 'QCarouselSlide' was not found in 'quasar'

**Comment by rstoenescu** [comment]
Quasar Play works fine.... Are you logging a bug for Quasar instead? Then that should go to Quasar repo. Regardless, have you added 'QCarousel' and 'QCarouselSlide' to quasar.conf.js > framework > components?
