### ISSUE TITLE
Support quasar 0.10.x

### ISSUE THREAD

**Issue by yieme** [quasarframework/quasar-play#5]
It appears work on this has begun. Any idea of when 0.10.x will be supported?
Excellent framework. Can't wait until it reaches 1.0

**Comment by rstoenescu** [comment]
Hi,

Thanks for the appreciations! What do you mean by "when 0.10.x will be supported"? Quasar Play currently uses latest v0.10.x (and it will be updated to the new v0.11 once it is released -- end of this week).

**Comment by yieme** [comment]
I see in `package.json` `"quasar-framework": "0.9.1"` as the dependency. I'm I missing something?

**Comment by rstoenescu** [comment]
I've symlinked Quasar from the node_modules to my dev folder. So builds are made with latest Quasar. Will update package.json too to avoid confusion.

**Comment by rstoenescu** [comment]
Done.
