### ISSUE TITLE
How to introduce online JS ? 如何引入在线js

### ISSUE THREAD

**Issue by royedia** [quasarframework/quasar-play#53]
Quasar has no webpack option. How to introduce online JS without making mistakes?

like
<script  type="text/javascript" src="xxxxxxxxxxxxxx" ></script>

**Comment by rstoenescu** [comment]
Hi,

Edit your index.template.html and make your necessary additions.
However, I think you are missing the point of webpack. Unless you really know what you are doing, you should "import" your JS file (from an app plugin or any .vue file).
