### ISSUE TITLE
Error when you click a Button when it is showing tooltip and set loading on

### ISSUE THREAD

**Issue by eminpala** [quasarframework/quasar-play#56]
It is happening when it is showing the tooltip. 

<q-btn icon="playlist_add" round  outline size="xs" class="float-right" color="primary" :loading="jLoading" @click="jLoading=true">
          <q-tooltip>Copy to New List</q-tooltip>
        </q-btn>

This is the error:
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by rstoenescu** [comment]
Hi,

There is a reason for the issue template existing. Please reopen at least with a jsfiddle. Thank you.
