### ISSUE TITLE
Events in popup-edit component get triggered twice

### ISSUE THREAD

**Issue by jvmonjo** [quasarframework/quasar-play#64]
### Software version

Quasar Play:
OS: OSX 10.13.6
Node: 8.11.3
NPM: 5.6.0
Browsers: Chrome 70
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
@save, @show or @hide event gets fired twice.

### What were you expecting?
@save, @show and @hide events should only be triggered once

### What steps did you take, to get the error?
bind @save to a method with `console.log('fired')`. The output you get is:
```
fired
fired
```

**Comment by rstoenescu** [comment]
I can't reproduce. Can you make a jsfiddle pls?

**Comment by jvmonjo** [comment]
Sure. Here is the jsfiddle:
[https://jsfiddle.net/jvmonjo/u4ct0d51/](https://jsfiddle.net/jvmonjo/u4ct0d51/)

**Comment by jvmonjo** [comment]
It seems that in Quasar v0.17.11 the issue has been fixed.

Thanks.
