### ISSUE TITLE
this line is incorrect

### ISSUE THREAD

**Issue by salar80** [quasarframework/quasar-play#67]
https://github.com/quasarframework/quasar-play/blob/96705044031034c2e4c71bfbe86f28e906fe81e3/src/pages/showcase/grouping/table/table-server-pagination.vue#L70

correct is 
` rows = this.tableData.slice(), `

**Comment by rstoenescu** [comment]
Hi,

`tableData` is not part of the Vue component.

https://github.com/quasarframework/quasar-play/blob/96705044031034c2e4c71bfbe86f28e906fe81e3/src/pages/showcase/grouping/table/table-server-pagination.vue#L26
