### ISSUE TITLE
Quasar Showcase bug

### ISSUE THREAD

**Issue by justdaft** [quasarframework/quasar-play#7]
Hi while playing with you showcase demo I noticed when you do the following

Click the 'Layout' link and then the 'About Link' you get a 404 error.

I have fixed this in my local repo by making the following change in 'router.js'

Original 
 {
    path: '/showcase/layout',
    component: load('showcase/layout/layout'),
    children: [
      {path: '', component: load('showcase/layout/about')},
      {path: 'toolbar', component: load('showcase/layout/toolbar')},
      {path: 'tabs', component: load('showcase/layout/tabs')},
      {path: 'drawer', component: load('showcase/layout/drawer')}
    ]
  }

Insert this 

{path: 'about', component: load('showcase/layout/about')},

Changed

{
    path: '/showcase/layout',
    component: load('showcase/layout/layout'),
    children: [
      {path: '', component: load('showcase/layout/about')},
      {path: 'toolbar', component: load('showcase/layout/toolbar')},
      {path: 'about', component: load('showcase/layout/about')},
      {path: 'tabs', component: load('showcase/layout/tabs')},
      {path: 'drawer', component: load('showcase/layout/drawer')}
    ]
  }

I am happy to make a pull request to fix this bug, thanks

Billy

**Comment by rstoenescu** [comment]
Hi, thanks for reporting and finding a solution!
PR would be great if you have some spare time. It would speed things up.

**Comment by justdaft** [comment]
Wow that was a quick reply, no problem I have been meaning to get involved
with something for a long time, I am very impressed with what you have
created.

Hopefully I can do it this morning.

Thanks
Billy

**Comment by rstoenescu** [comment]
Merged PR. Closing.
