### ISSUE TITLE
Quasar Play Dialog Example throwing in the console for some examples

### ISSUE THREAD

**Issue by sganz** [quasarframework/quasar-play#70]
### Software version
Testing this on the https://quasar-framework.org/components/dialog.html page as of the day of this report.

Quasar Play: Live web, looks like last update was - Wed Jul 25 2018.
Browser: FF 63.0.3 (64-bit) Windows 

### What did you get as the error?
Was on the dialog page - https://quasar-framework.org/components/dialog.html and when watching the console on FF 63.0.3 (64-bit) Windows I noticed a few exceptions being thrown -

```
Unhandled promise rejection Error: ""
	u https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:18:392737
	e https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:7:12610
	emit https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:7:16415
	dismiss https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:18:210833
	e https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:7:12610
	emit https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:7:16415
	__dismiss https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:18:63119
	s https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:13:28041
	A https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:13:28191
	c https://quasar-framework.org/quasar-play/android/js/vendor.d9cfc621.js:13:40345
```

### What were you expecting?
Clean log

### What steps did you take, to get the error?
Near the bottom on the test portion of the screen I went to the Appear from Edges section (near the bottom of the examples) and clicked 'Dialog from top'. The dialog will pop up, and if you do not click the 'OK' button but click off screen you will close the dialog and see an exception in the log. 

Not sure if a component issue or the way the example code was written but it seems to only happen with those specific tests under `Appear from Edges section` of the examples (Top, bottom, left right).

**Comment by rstoenescu** [comment]
Hi,

Just to note this is not a bug in Quasar. For < v1.0, Dialogs return Promises, and in this Quasar Play case, not all of them have a `catch() {..}` attached to them. Will add it to eliminate confusion though.

**Comment by rstoenescu** [comment]
Will be available on next website update.

**Comment by sganz** [comment]
No worries, figured the Quasar Play was just doing something different then it should. Keep up the fantastic work.
