### ISSUE TITLE
QLayoutDrawer  set  no-swipe-close = 'false' 

### ISSUE THREAD

**Issue by HappyLeiLei** [quasarframework/quasar-play#76]
QLayoutDrawer 
set  no-swipe-close = 'false' 
error: Invalid prop: type check failed for prop "noSwipeOpen". Expected Boolean, got String.

**Comment by rstoenescu** [comment]
Hi,

You are setting a String... Bind it to the value of `false`, do not simply supply the String 'false'.
`<q-layout-drawer :no-swipe-close="false" ...`

Or simply don't specify it. Boolean props are "false" by default.
